#############################################################################
# Makefile for building: ksoft-rc-simulator
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  ksoft-rc-simulator.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ksoft-rc-simulator.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DPLATFORMIO=30600 -DARDUINO_AVR_UNO -DF_CPU=16000000L -DARDUINO_ARCH_AVR -DARDUINO=10805 -D__AVR_ATmega328P__ -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../.platformio/packages/framework-arduino-avr/cores/arduino -I../../.platformio/packages/framework-arduino-avr/variants/standard -I/home/lukidrone/.platformio/packages/framework-arduinoavr/libraries/SoftwareSerial/src -I/home/lukidrone/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/EEPROM/src -I/home/lukidrone/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/HID/src -I/home/lukidrone/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/SPI/src -I/home/lukidrone/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/SoftwareSerial/src -I/home/lukidrone/.platformio/packages/framework-arduinoavr/libraries/__cores__/arduino/Wire/src -I../../.platformio/packages/toolchain-atmelavr/avr/include -I/home/lukidrone/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include -I/home/lukidrone/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.9.2/include-fixed -I../../.platformio/packages/tool-unity -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ksoft-rc-simulator1.0.0
DISTDIR = /home/lukidrone/workspace/ksoft-rc-simulator/.tmp/ksoft-rc-simulator1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp 
OBJECTS       = main.o
DIST          = platformio.ini \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ksoft-rc-simulator.pro  src/main.cpp
QMAKE_TARGET  = ksoft-rc-simulator
DESTDIR       = 
TARGET        = ksoft-rc-simulator


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ksoft-rc-simulator.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ksoft-rc-simulator.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile ksoft-rc-simulator.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ksoft-rc-simulator.pro:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ksoft-rc-simulator.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: src/main.cpp ../../.platformio/packages/framework-arduino-avr/cores/arduino/Arduino.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/stdlib.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/string.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/math.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/pgmspace.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/inttypes.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/stdint.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/sfr_defs.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioat94k.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io43u32x.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io43u35x.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io76c711.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io86r401.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io90pwm1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io90pwmx.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io90pwm2b.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io90pwm3b.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io90pwm216.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io90pwm316.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io90pwm161.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io90pwm81.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom8u2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom16m1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom16u2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom16u4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom32c1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom32m1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom32u2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom32u4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom32u6.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom64c1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom64m1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom128.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom128a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom1280.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iomxx0_1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom1281.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom1284.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom1284p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom128rfa1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom1284rfr2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom128rfr2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom2564rfr2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom256rfr2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom2560.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom2561.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iocan32.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iocanxx.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iocan64.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iocan128.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iousb82.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iousbxx2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iousb162.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iousb646.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iousbxx6_7.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iousb647.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iousb1286.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iousb1287.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom644rfr2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom64rfr2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom64.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom64a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom640.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom644.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iomxx4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom644a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom644p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom644pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom645.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom645a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom645p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom6450.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom6450a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom6450p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom649.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom649a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom6490.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom6490a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom6490p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom649p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom64hve.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom64hve2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom103.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom32.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom32a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom323.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom324p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom324a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom324pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom325.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom325a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom325p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom325pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom3250.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom3250a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom3250p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom3250pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom328p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom328.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom329.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom329a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom329p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom329pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom3290pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom3290.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom3290a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom32hvb.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom32hvbrevb.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom406.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom16.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom16a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom161.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom162.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom163.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom164p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom164.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom164a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom164pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom165.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom165a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom165p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom165pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom168.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iomx8.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom168a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom168p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom168pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom168pb.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom169.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom169a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom169p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom169pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom8hva.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iomxxhva.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom16hva.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom16hva2.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom16hvb.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom16hvbrevb.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom8.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom8a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom48.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom48a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom48pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom48pb.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom48p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom88.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom88a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom88p.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom88pa.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom88pb.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom8515.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom8535.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io8535.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io8534.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io8515.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io4434.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io4433.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io4414.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn22.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn26.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io2343.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io2333.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io2323.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io2313.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn5.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn9.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn10.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn20.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn40.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn2313.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn2313a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn13.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn13a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn25.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotnx5.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn4313.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn45.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn85.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn24.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotnx4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn24a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn44.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn44a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn441.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn84.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn84a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn841.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn261.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotnx61.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn261a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn461.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn461a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn861.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn861a.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn43u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn48.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn88.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn828.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn87.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn167.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn1634.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io90scr100.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox8e5.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox16a4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox16a4u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox16c4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox16d4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox16e5.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox32a4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox32a4u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox32c3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox32c4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox32d3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox32d4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox32e5.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64a1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64a1u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64a3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64a3u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64a4u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64b1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64b3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64c3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64d3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox64d4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128a1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128a1u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128a4u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128a3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128a3u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128b1.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128b3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128c3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128d3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox128d4.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox192a3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox192a3u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox192c3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox192d3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox256a3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox256a3u.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox256a3b.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox256a3bu.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox256c3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox256d3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox384c3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iox384d3.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa5702m322.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa5782.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa5790.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa5790n.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa5791.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa5831.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa5272.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa5505.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa5795.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa6285.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa6286.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa6289.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa6612c.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa6613c.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa6614q.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa6616c.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa6617c.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa664251.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa8210.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/ioa8510.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn28.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/io1200.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn15.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn12.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iotn11.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/iom3000.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/portpins.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/common.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/version.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/xmega.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/fuse.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/lock.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/interrupt.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/binary.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/WCharacter.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/ctype.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/WString.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/HardwareSerial.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/Stream.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/Print.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/stdio.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/Printable.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/USBAPI.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/avr/eeprom.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/util/delay.h \
		../../.platformio/packages/toolchain-atmelavr/avr/include/util/delay_basic.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/USBDesc.h \
		../../.platformio/packages/framework-arduino-avr/cores/arduino/USBCore.h \
		../../.platformio/packages/framework-arduino-avr/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

